"""Telegram MUBA Camera Mini App.

Live camera capture is preferred. The source frame is held only in browser/request memory
and is sent after explicit transformation action. No source image is published to Gallery.
"""

def camera_html(base_url:str)->str:
    b=base_url.rstrip("/")
    return f"""<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta http-equiv="Cache-Control" content="no-store"><script src="https://telegram.org/js/telegram-web-app.js"></script>
<style>*{{box-sizing:border-box}}body{{margin:0;background:#07040f;color:#fff;font-family:system-ui;padding:20px}}.card{{max-width:620px;margin:auto;background:#120a1f;border:1px solid #7c3aed;border-radius:22px;padding:20px}}h1{{margin:0 0 8px}}p,small{{color:#c8b9dc;line-height:1.45}}button,a{{width:100%;display:block;text-align:center;border:0;border-radius:13px;padding:14px;font-weight:750;text-decoration:none}}button{{background:linear-gradient(135deg,#b026ff,#7c3aed);color:#fff;margin-top:10px}}button:disabled{{opacity:.65}}video,#preview,#out{{display:none;width:100%;margin-top:14px;border-radius:16px;background:#000}}#progress{{display:none;margin-top:12px;height:12px;background:#090510;border:1px solid #51326f;border-radius:999px;overflow:hidden}}#bar{{width:0;height:100%;background:linear-gradient(90deg,#7c3aed,#d946ef);transition:width .35s ease}}#msg{{margin-top:10px;text-align:center;color:#d8c7ee}}#status,#resultTitle{{display:none;margin-top:10px;color:#86efac;font-weight:800}}#save{{display:none;margin-top:10px;background:#241638;color:#fff}}#receipt{{margin-top:14px;color:#86efac;white-space:pre-line}}.privacy{{padding:12px;border:1px solid #51326f;border-radius:12px;background:#090510}}</style></head><body><div class="card">
<h1>📸 MUBA CAMERA</h1><div class="privacy"><strong>AL → İŞLE → VER</strong><p>Günlük üretim hakkı: 1. Başarısız işlem hakkından düşmez. Kamera görüntüsü yalnızca MUBA dönüşümü için kullanılır; kaynak görüntü Gallery, veritabanı veya dosya deposuna kaydedilmez.</p><small>Kamera izni cihaz tarafından sorulur. AI işlemi harici model sağlayıcısında gerçekleşir.</small></div>
<button id="openCamera">📷 KAMERAYI AÇ</button><video id="camera" autoplay playsinline muted></video><button id="take" style="display:none">📸 FOTOĞRAFI ÇEK</button><canvas id="canvas" style="display:none"></canvas><div id="status">Fotoğraf çekildi ✓</div><img id="preview" alt="Captured camera frame"><button id="go" disabled>MUBA DÖNÜŞ</button><div id="progress"><div id="bar"></div></div><div id="msg"></div><div id="resultTitle">MUBA'N HAZIR ✓</div><img id="out" alt="Generated MUBA"><a id="save" download="my-muba.png">⬇️ SONUCU KAYDET</a><div id="receipt"></div>
</div><script>
const tg=window.Telegram.WebApp;tg.ready();tg.expand();
let stream=null,capturedBlob=null,resultUrl="",previewUrl="";
const openBtn=document.getElementById("openCamera"),video=document.getElementById("camera"),take=document.getElementById("take"),canvas=document.getElementById("canvas"),status=document.getElementById("status"),preview=document.getElementById("preview"),go=document.getElementById("go"),msg=document.getElementById("msg"),progress=document.getElementById("progress"),bar=document.getElementById("bar"),receipt=document.getElementById("receipt");
function stopCamera(){{if(stream){{stream.getTracks().forEach(t=>t.stop());stream=null}}}}
openBtn.onclick=async()=>{{msg.textContent="Kamera açılıyor...";try{{if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia)throw new Error("Bu Telegram sürümü canlı kamera erişimini desteklemiyor.");stream=await navigator.mediaDevices.getUserMedia({{video:{{facingMode:"user"}},audio:false}});video.srcObject=stream;video.style.display="block";take.style.display="block";openBtn.textContent="🔄 KAMERAYI YENİDEN AÇ";msg.textContent="Kamera hazır ✓"}}catch(e){{msg.textContent="Kamera açılamadı: "+e.message}}}};
take.onclick=()=>{{if(!stream||!video.videoWidth){{msg.textContent="Kamera henüz hazır değil.";return}}const max=1280,scale=Math.min(1,max/video.videoWidth);canvas.width=Math.round(video.videoWidth*scale);canvas.height=Math.round(video.videoHeight*scale);canvas.getContext("2d").drawImage(video,0,0,canvas.width,canvas.height);canvas.toBlob(blob=>{{if(!blob){{msg.textContent="Fotoğraf alınamadı.";return}}capturedBlob=blob;if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=URL.createObjectURL(blob);preview.src=previewUrl;preview.style.display="block";status.style.display="block";go.disabled=false;msg.textContent="Fotoğraf hazır. MUBA DÖNÜŞ'e bas.";stopCamera();video.style.display="none";take.style.display="none"}}, "image/jpeg", .9)}};
go.onclick=async()=>{{if(!capturedBlob){{msg.textContent="Önce kameradan fotoğraf çek.";return}}let pct=10,timer=null,done=false;const draw=()=>{{bar.style.width=pct+"%";go.textContent="MUBA DÖNÜŞ %"+pct;msg.textContent=pct<35?"AL %"+pct:pct<90?"İŞLE %"+pct:"MUBA hazırlanıyor %"+pct}};go.disabled=true;progress.style.display="block";draw();timer=setInterval(()=>{{if(pct<90){{pct=Math.min(90,pct+(pct<50?10:5));draw()}}}},700);const fd=new FormData();fd.append("photo",capturedBlob,"camera.jpg");fd.append("initData",tg.initData||"");const q=new URLSearchParams(location.search);fd.append("uid",q.get("uid")||"");fd.append("studioToken",q.get("st")||"");receipt.textContent="";try{{const r=await fetch("{b}/camera/generate",{{method:"POST",body:fd,cache:"no-store"}});if(!r.ok){{let e={{}};try{{e=await r.json()}}catch(_){{}}throw new Error(e.error||("İşlem başarısız ("+r.status+")."))}}const blob=await r.blob();if(!blob.size)throw new Error("Üretim sonucu boş geldi.");done=true;pct=100;draw();if(resultUrl)URL.revokeObjectURL(resultUrl);resultUrl=URL.createObjectURL(blob);const out=document.getElementById("out"),save=document.getElementById("save");out.src=resultUrl;out.style.display="block";document.getElementById("resultTitle").style.display="block";save.href=resultUrl;save.style.display="block";msg.textContent="MUBA hazır ✓";const rem=r.headers.get("X-MUBA-Remaining");receipt.textContent="PRIVACY RECEIPT ✓\nKaynak fotoğraf: MUBA tarafından kalıcı kaydedilmedi\nGallery: yayınlanmadı\nSonuç: cihazına teslim edildi\nGünlük hak: "+(rem==="DEV"?"DEV":rem+"/1 kaldı")}}catch(e){{msg.textContent="Üretim hatası: "+e.message}}finally{{if(timer)clearInterval(timer);if(done){{bar.style.width="100%";go.textContent="MUBA DÖNÜŞ %100 ✓"}}else{{go.disabled=false;go.textContent="MUBA DÖNÜŞ — TEKRAR DENE";progress.style.display="none";bar.style.width="0"}}}}}};
window.addEventListener("pagehide",stopCamera);
</script></body></html>"""
