"""Telegram MUBA Camera Mini App.

Live camera capture is preferred. The source frame is held only in browser/request memory
and is sent after explicit transformation action. No source image is published to Gallery.
"""

def camera_html(base_url:str,lang:str="tr")->str:
    b=base_url.rstrip("/")
    page=rf"""<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta http-equiv="Cache-Control" content="no-store"><script src="https://telegram.org/js/telegram-web-app.js"></script>
<style>*{{box-sizing:border-box}}body{{margin:0;background:#07040f;color:#fff;font-family:system-ui;padding:20px}}.card{{max-width:620px;margin:auto;background:#120a1f;border:1px solid #7c3aed;border-radius:22px;padding:20px}}h1{{margin:0 0 8px}}p,small{{color:#c8b9dc;line-height:1.45}}button,a{{width:100%;display:block;text-align:center;border:0;border-radius:13px;padding:14px;font-weight:750;text-decoration:none}}button{{background:linear-gradient(135deg,#b026ff,#7c3aed);color:#fff;margin-top:10px}}button:disabled{{opacity:.65}}video,#preview,#out{{display:none;width:100%;margin-top:14px;border-radius:16px;background:#000}}#progress{{display:none;margin-top:12px;height:12px;background:#090510;border:1px solid #51326f;border-radius:999px;overflow:hidden}}#bar{{width:0;height:100%;background:linear-gradient(90deg,#7c3aed,#d946ef);transition:width .35s ease}}#msg{{margin-top:10px;text-align:center;color:#d8c7ee}}#status,#resultTitle{{display:none;margin-top:10px;color:#86efac;font-weight:800}}#save{{display:none;margin-top:10px;background:#241638;color:#fff}}#receipt{{margin-top:14px;color:#86efac;white-space:pre-line}}.privacy{{padding:12px;border:1px solid #51326f;border-radius:12px;background:#090510}}</style></head><body><div class="card">
<h1>📸 MUBA CAMERA</h1><div class="privacy"><strong>AL → İŞLE → VER</strong><p>Günlük üretim hakkı: 1. Başarısız işlem hakkından düşmez. Kamera görüntüsü yalnızca MUBA dönüşümü için kullanılır; kaynak görüntü Gallery, veritabanı veya dosya deposuna kaydedilmez.</p><small>Kamera izni cihaz tarafından sorulur. AI işlemi harici model sağlayıcısında gerçekleşir.</small></div>
<button id="openCamera">📷 KAMERAYI AÇ</button><input id="cameraFallback" type="file" accept="image/*" capture="user" style="display:none"><video id="camera" autoplay playsinline muted></video><button id="take" style="display:none">📸 FOTOĞRAFI ÇEK</button><canvas id="canvas" style="display:none"></canvas><div id="status">Fotoğraf çekildi ✓</div><img id="preview" alt="Captured camera frame"><button id="go" disabled>MUBA DÖNÜŞ</button><div id="progress"><div id="bar"></div></div><div id="msg"></div><div id="resultTitle">MUBA'N HAZIR ✓</div><img id="out" alt="Generated MUBA"><a id="save" download="my-muba.png">⬇️ SONUCU KAYDET</a><div id="receipt"></div>
</div><script>
const tg=window.Telegram.WebApp;tg.ready();tg.expand();
let stream=null,capturedBlob=null,resultUrl="",previewUrl="";
const openBtn=document.getElementById("openCamera"),fallback=document.getElementById("cameraFallback"),video=document.getElementById("camera"),take=document.getElementById("take"),canvas=document.getElementById("canvas"),status=document.getElementById("status"),preview=document.getElementById("preview"),go=document.getElementById("go"),msg=document.getElementById("msg"),progress=document.getElementById("progress"),bar=document.getElementById("bar"),receipt=document.getElementById("receipt");
function stopCamera(){{if(stream){{stream.getTracks().forEach(t=>t.stop());stream=null}}}}
function useCapturedBlob(blob){{if(!blob)return;capturedBlob=blob;if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=URL.createObjectURL(blob);preview.src=previewUrl;preview.style.display="block";status.style.display="block";go.disabled=false;msg.textContent="Fotoğraf hazır. MUBA DÖNÜŞ'e bas.";stopCamera();video.style.display="none";take.style.display="none"}}
openBtn.onclick=async()=>{{msg.textContent="Kamera açılıyor...";try{{if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia)throw new Error("webview-camera-unavailable");stream=await navigator.mediaDevices.getUserMedia({{video:{{facingMode:"user"}},audio:false}});video.srcObject=stream;video.style.display="block";take.style.display="block";openBtn.textContent="🔄 KAMERAYI YENİDEN AÇ";msg.textContent="Kamera hazır ✓"}}catch(e){{msg.textContent="Cihaz kamerası açılıyor...";fallback.click()}}}};
fallback.onchange=()=>{{const file=fallback.files&&fallback.files[0];if(file)useCapturedBlob(file);fallback.value=""}};
take.onclick=()=>{{if(!stream||!video.videoWidth){{msg.textContent="Kamera henüz hazır değil.";return}}const max=1280,scale=Math.min(1,max/video.videoWidth);canvas.width=Math.round(video.videoWidth*scale);canvas.height=Math.round(video.videoHeight*scale);canvas.getContext("2d").drawImage(video,0,0,canvas.width,canvas.height);canvas.toBlob(blob=>{{if(!blob){{msg.textContent="Fotoğraf alınamadı.";return}}capturedBlob=blob;if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=URL.createObjectURL(blob);preview.src=previewUrl;preview.style.display="block";status.style.display="block";go.disabled=false;msg.textContent="Fotoğraf hazır. MUBA DÖNÜŞ'e bas.";stopCamera();video.style.display="none";take.style.display="none"}}, "image/jpeg", .9)}};
go.onclick=async()=>{{if(!capturedBlob){{msg.textContent="Önce kameradan fotoğraf çek.";return}}let pct=10,timer=null,done=false;const draw=()=>{{bar.style.width=pct+"%";go.textContent="MUBA DÖNÜŞ %"+pct;msg.textContent=pct<35?"AL %"+pct:pct<90?"İŞLE %"+pct:"MUBA hazırlanıyor %"+pct}};go.disabled=true;progress.style.display="block";draw();timer=setInterval(()=>{{if(pct<90){{pct=Math.min(90,pct+(pct<50?10:5));draw()}}}},700);const fd=new FormData();fd.append("photo",capturedBlob,"camera.jpg");fd.append("initData",tg.initData||"");const q=new URLSearchParams(location.search);fd.append("uid",q.get("uid")||"");fd.append("studioToken",q.get("st")||"");receipt.textContent="";try{{const r=await fetch("{b}/camera/generate",{{method:"POST",body:fd,cache:"no-store"}});if(!r.ok){{let e={{}};try{{e=await r.json()}}catch(_){{}}throw new Error(e.code==="provider_quota"?"Sağlayıcı kotası kullanılamıyor. Üretim duraklatıldı; diğer MUBA alanları çalışıyor.":"İşlem başarısız ("+r.status+").")}}const blob=await r.blob();if(!blob.size)throw new Error("Üretim sonucu boş geldi.");done=true;pct=100;draw();if(resultUrl)URL.revokeObjectURL(resultUrl);resultUrl=URL.createObjectURL(blob);const out=document.getElementById("out"),save=document.getElementById("save");out.src=resultUrl;out.style.display="block";document.getElementById("resultTitle").style.display="block";save.href=resultUrl;save.style.display="block";msg.textContent="MUBA hazır ✓";const rem=r.headers.get("X-MUBA-Remaining");receipt.textContent="PRIVACY RECEIPT ✓\nKaynak fotoğraf: MUBA tarafından kalıcı kaydedilmedi\nGallery: yayınlanmadı\nSonuç: cihazına teslim edildi\nGünlük hak: "+(rem==="DEV"?"DEV":rem+"/1 kaldı")}}catch(e){{msg.textContent="Üretim hatası: "+e.message}}finally{{if(timer)clearInterval(timer);if(done){{bar.style.width="100%";go.textContent="MUBA DÖNÜŞ %100 ✓"}}else{{go.disabled=false;go.textContent="MUBA DÖNÜŞ — TEKRAR DENE";progress.style.display="none";bar.style.width="0"}}}}}};
window.addEventListener("pagehide",stopCamera);
</script></body></html>"""

    lang=lang if lang in ("en","tr","zh","ar","hi") else "en"
    page=page.replace('<html>', '<html lang="'+lang+'"'+(' dir="rtl"' if lang=="ar" else '')+'>')
    index=("en","tr","zh","ar","hi").index(lang)
    for original,values in sorted(CAMERA_COPY.items(),key=lambda row:len(row[0]),reverse=True):
        page=page.replace(original,values[index])
    return page

CAMERA_COPY={
    "Sağlayıcı kotası kullanılamıyor. Üretim duraklatıldı; diğer MUBA alanları çalışıyor.":("Provider quota unavailable. Generation is paused; other MUBA areas remain available.","Sağlayıcı kotası kullanılamıyor. Üretim duraklatıldı; diğer MUBA alanları çalışıyor.","服务商配额暂不可用。生成已暂停；MUBA 其他功能仍可使用。","حصة المزوّد غير متاحة. أُوقف الإنتاج وتبقى بقية خدمات MUBA متاحة.","प्रदाता कोटा उपलब्ध नहीं है। निर्माण रुका है; MUBA के बाकी हिस्से उपलब्ध हैं।"),
    'AL → İŞLE → VER':('RECEIVE → PROCESS → RETURN', 'AL → İŞLE → VER', '接收 → 处理 → 返回', 'استلام → معالجة → تسليم', 'प्राप्त करें → रूपांतरण → लौटाएँ'),
    'Günlük üretim hakkı: 1. Başarısız işlem hakkından düşmez. Kamera görüntüsü yalnızca MUBA dönüşümü için kullanılır; kaynak görüntü Gallery, veritabanı veya dosya deposuna kaydedilmez.':('Daily allowance: 1. Failed attempts do not use it. The photo is used only for MUBA transformation; the source is not saved in Gallery, database or file storage.', 'Günlük üretim hakkı: 1. Başarısız işlem hakkından düşmez. Kamera görüntüsü yalnızca MUBA dönüşümü için kullanılır; kaynak görüntü Gallery, veritabanı veya dosya deposuna kaydedilmez.', '每日次数：1。失败不消耗次数。照片仅用于 MUBA 转换，原图不保存在 Gallery、数据库或文件存储中。', 'فرصة يومية واحدة. المحاولات الفاشلة لا تستهلكها. تُستخدم الصورة لتحويل MUBA فقط ولا تُحفظ في Gallery أو قاعدة البيانات أو مخزن الملفات.', 'दैनिक मौका: 1। विफल प्रयास में मौका नहीं कटता। फोटो केवल MUBA रूपांतरण के लिए है; मूल फोटो Gallery, डेटाबेस या फ़ाइल भंडार में नहीं सहेजी जाती।'),
    'Kamera izni cihaz tarafından sorulur. AI işlemi harici model sağlayıcısında gerçekleşir.':('Your device requests camera permission. AI processing takes place at an external model provider.', 'Kamera izni cihaz tarafından sorulur. AI işlemi harici model sağlayıcısında gerçekleşir.', '设备会请求相机权限。AI 处理由外部模型提供商完成。', 'يطلب الجهاز إذن الكاميرا. تتم معالجة الذكاء الاصطناعي لدى مزوّد نموذج خارجي.', 'डिवाइस कैमरे की अनुमति माँगता है। AI रूपांतरण बाहरी मॉडल प्रदाता पर होता है।'),
    '📷 KAMERAYI AÇ':('📷 OPEN CAMERA', '📷 KAMERAYI AÇ', '📷 打开相机', '📷 افتح الكاميرا', '📷 कैमरा खोलें'),
    '📸 FOTOĞRAFI ÇEK':('📸 TAKE PHOTO', '📸 FOTOĞRAFI ÇEK', '📸 拍照', '📸 التقط الصورة', '📸 फोटो लें'),
    'Fotoğraf çekildi ✓':('Photo captured ✓', 'Fotoğraf çekildi ✓', '照片已拍摄 ✓', 'تم التقاط الصورة ✓', 'फोटो ली गई ✓'),
    "MUBA'N HAZIR ✓":('Your MUBA is ready ✓', "MUBA'N HAZIR ✓", '你的 MUBA 已准备好 ✓', 'MUBA الخاص بك جاهز ✓', 'आपका MUBA तैयार है ✓'),
    '⬇️ SONUCU KAYDET':('⬇️ SAVE RESULT', '⬇️ SONUCU KAYDET', '⬇️ 保存结果', '⬇️ احفظ النتيجة', '⬇️ परिणाम सहेजें'),
    '🔄 KAMERAYI YENİDEN AÇ':('🔄 REOPEN CAMERA', '🔄 KAMERAYI YENİDEN AÇ', '🔄 重新打开相机', '🔄 أعد فتح الكاميرا', '🔄 कैमरा फिर खोलें'),
    'Kamera açılıyor...':('Opening camera…', 'Kamera açılıyor...', '正在打开相机…', 'جارٍ فتح الكاميرا…', 'कैमरा खुल रहा है…'),
    'Kamera hazır ✓':('Camera ready ✓', 'Kamera hazır ✓', '相机已准备好 ✓', 'الكاميرا جاهزة ✓', 'कैमरा तैयार है ✓'),
    'Cihaz kamerası açılıyor...':('Opening device camera…', 'Cihaz kamerası açılıyor...', '正在打开设备相机…', 'جارٍ فتح كاميرا الجهاز…', 'डिवाइस कैमरा खुल रहा है…'),
    'Kamera henüz hazır değil.':('Camera is not ready yet.', 'Kamera henüz hazır değil.', '相机尚未准备好。', 'الكاميرا غير جاهزة بعد.', 'कैमरा अभी तैयार नहीं है।'),
    'Fotoğraf alınamadı.':('Could not capture photo.', 'Fotoğraf alınamadı.', '无法拍摄照片。', 'تعذر التقاط الصورة.', 'फोटो नहीं ली जा सकी।'),
    "Fotoğraf hazır. MUBA DÖNÜŞ'e bas.":('Photo ready. Press MUBA TRANSFORM.', "Fotoğraf hazır. MUBA DÖNÜŞ'e bas.", '照片已准备好。请点击 MUBA 转换。', 'الصورة جاهزة. اضغط تحويل MUBA.', 'फोटो तैयार है। MUBA रूपांतरण दबाएँ।'),
    'Önce kameradan fotoğraf çek.':('Take a photo first.', 'Önce kameradan fotoğraf çek.', '请先拍照。', 'التقط صورة أولاً.', 'पहले फोटो लें।'),
    'İşlem başarısız (':('Request failed (', 'İşlem başarısız (', '请求失败（', 'فشل الطلب (', 'अनुरोध विफल ('),
    'Üretim sonucu boş geldi.':('No generated image was returned.', 'Üretim sonucu boş geldi.', '未返回生成图片。', 'لم يتم إرجاع صورة مولّدة.', 'तैयार चित्र नहीं मिला।'),
    'MUBA hazır ✓':('MUBA ready ✓', 'MUBA hazır ✓', 'MUBA 已准备好 ✓', 'MUBA جاهز ✓', 'MUBA तैयार है ✓'),
    'Üretim hatası: ':('Generation error: ', 'Üretim hatası: ', '生成错误：', 'خطأ في الإنتاج: ', 'चित्र निर्माण त्रुटि: '),
    'MUBA DÖNÜŞ — TEKRAR DENE':('MUBA TRANSFORM — RETRY', 'MUBA DÖNÜŞ — TEKRAR DENE', 'MUBA 转换 — 重试', 'تحويل MUBA — حاول مجدداً', 'MUBA रूपांतरण — फिर कोशिश करें'),
    'MUBA DÖNÜŞ':('MUBA TRANSFORM', 'MUBA DÖNÜŞ', 'MUBA 转换', 'تحويل MUBA', 'MUBA रूपांतरण'),
    'AL %':('RECEIVE %', 'AL %', '接收 %', 'استلام %', 'प्राप्ति %'),
    'İŞLE %':('PROCESS %', 'İŞLE %', '处理 %', 'معالجة %', 'रूपांतरण %'),
    'MUBA hazırlanıyor %':('Preparing MUBA %', 'MUBA hazırlanıyor %', '正在准备 MUBA %', 'جارٍ إعداد MUBA %', 'MUBA तैयार हो रहा है %'),
    'Captured camera frame':('Captured photo', 'Çekilen fotoğraf', '拍摄的照片', 'الصورة الملتقطة', 'ली गई फोटो'),
    'Generated MUBA':('Generated MUBA', 'Üretilen MUBA', '生成的 MUBA', 'MUBA المولّد', 'तैयार MUBA चित्र'),
    'PRIVACY RECEIPT ✓\\nKaynak fotoğraf: MUBA tarafından kalıcı kaydedilmedi\\nGallery: yayınlanmadı\\nSonuç: cihazına teslim edildi\\nGünlük hak: ':('PRIVACY RECEIPT ✓\\nSource photo: not permanently saved by MUBA\\nGallery: not published\\nResult: delivered to your device\\nDaily allowance: ', 'GİZLİLİK BİLGİSİ ✓\\nKaynak fotoğraf: MUBA tarafından kalıcı kaydedilmedi\\nGallery: yayınlanmadı\\nSonuç: cihazına teslim edildi\\nGünlük hak: ', '隐私说明 ✓\\n原照片：MUBA 未永久保存\\nGallery：未发布\\n结果：已交付到你的设备\\n每日次数：', 'إيصال الخصوصية ✓\\nالصورة الأصلية: لم يحفظها MUBA بشكل دائم\\nGallery: لم تُنشر\\nالنتيجة: سُلّمت إلى جهازك\\nالفرصة اليومية: ', 'गोपनीयता विवरण ✓\\nमूल फोटो: MUBA ने स्थायी रूप से नहीं सहेजी\\nGallery: प्रकाशित नहीं\\nपरिणाम: डिवाइस पर दिया गया\\nदैनिक मौका: '),
    '/1 kaldı':('/1 remaining', '/1 kaldı', '/1 剩余', '/1 متبقية', '/1 बाकी'),
}
